// Wehrung's Smart Deck Estimator - Product Catalog

import type {
  JurisdictionProfile,
  StockCatalog,
  DeckingBrand,
  RailingSystem,
} from "./types";

// Jurisdiction profile - East Coast default
export const jurisdictionProfile: JurisdictionProfile = {
  id: "east-coast-default",
  label: "East Coast Default",
  soilBearingPsf: 2000,
  frostDepthIn: 36,
  defaultSonotubeLengthIn: 48,
  coastalMode: false,
  bagYieldCf80: 0.6,
  bagYieldCf60: 0.45,
};

// Stock catalog
export const stockCatalog: StockCatalog = {
  framingLengthsFt: [8, 10, 12, 14, 16, 18, 20],
  sonotubeDiametersIn: [10, 12, 14, 16, 18, 20, 22, 24],
  transformerSizesW: [45, 60, 100, 150, 200, 300],
};

// Joist span lookup (conservative prescriptive profile)
export const joistSpanLookup: Record<12 | 16, Record<string, number>> = {
  12: {
    "2x6": 9.5,
    "2x8": 12.5,
    "2x10": 15.67,
    "2x12": 18,
  },
  16: {
    "2x6": 8.33,
    "2x8": 11.08,
    "2x10": 13.58,
    "2x12": 15.75,
  },
};

// 3-ply beam span lookup (joists framing from one side only)
export const beamSpanLookup: Record<number, Record<string, number>> = {
  6: { "3-2x8": 9.42, "3-2x10": 11.75, "3-2x12": 13.67 },
  8: { "3-2x8": 8.25, "3-2x10": 10.17, "3-2x12": 11.83 },
  10: { "3-2x8": 7.33, "3-2x10": 9.08, "3-2x12": 10.5 },
  12: { "3-2x8": 6.67, "3-2x10": 8.25, "3-2x12": 9.58 },
  14: { "3-2x8": 6.17, "3-2x10": 7.58, "3-2x12": 8.83 },
  16: { "3-2x8": 5.75, "3-2x10": 7.08, "3-2x12": 8.25 },
  18: { "3-2x8": 5.42, "3-2x10": 6.67, "3-2x12": 7.83 },
};

// Decking brands catalog
export const deckingBrands: DeckingBrand[] = [
  {
    id: "trex",
    name: "Trex",
    collections: [
      {
        id: "trex-enhance-naturals",
        name: "Enhance Naturals",
        brand: "Trex",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 0.94,
        colors: [
          {
            name: "Toasted Sand",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-enhance-hidden",
            screwSkuGroup: "trex-enhance-screws",
            plugSkuGroup: "trex-enhance-plugs",
          },
          {
            name: "Cinnamon Cove",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-enhance-hidden",
            screwSkuGroup: "trex-enhance-screws",
            plugSkuGroup: "trex-enhance-plugs",
          },
          {
            name: "Rocky Harbour",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-enhance-hidden",
            screwSkuGroup: "trex-enhance-screws",
            plugSkuGroup: "trex-enhance-plugs",
          },
          {
            name: "Foggy Wharf",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-enhance-hidden",
            screwSkuGroup: "trex-enhance-screws",
            plugSkuGroup: "trex-enhance-plugs",
          },
          {
            name: "Honey Grove",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-enhance-hidden",
            screwSkuGroup: "trex-enhance-screws",
            plugSkuGroup: "trex-enhance-plugs",
          },
          {
            name: "Golden Hour",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-enhance-hidden",
            screwSkuGroup: "trex-enhance-screws",
            plugSkuGroup: "trex-enhance-plugs",
          },
        ],
      },
      {
        id: "trex-select",
        name: "Select",
        brand: "Trex",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 0.82,
        colors: [
          {
            name: "Whiskey Barrel",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-select-hidden",
            screwSkuGroup: "trex-select-screws",
            plugSkuGroup: "trex-select-plugs",
          },
          {
            name: "Millstone",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-select-hidden",
            screwSkuGroup: "trex-select-screws",
            plugSkuGroup: "trex-select-plugs",
          },
        ],
      },
      {
        id: "trex-transcend",
        name: "Transcend",
        brand: "Trex",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 0.94,
        colors: [
          {
            name: "Rope Swing",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-transcend-hidden",
            screwSkuGroup: "trex-transcend-screws",
            plugSkuGroup: "trex-transcend-plugs",
          },
          {
            name: "Havana Gold",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-transcend-hidden",
            screwSkuGroup: "trex-transcend-screws",
            plugSkuGroup: "trex-transcend-plugs",
          },
          {
            name: "Lava Rock",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-transcend-hidden",
            screwSkuGroup: "trex-transcend-screws",
            plugSkuGroup: "trex-transcend-plugs",
          },
          {
            name: "Tiki Torch",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-transcend-hidden",
            screwSkuGroup: "trex-transcend-screws",
            plugSkuGroup: "trex-transcend-plugs",
          },
          {
            name: "Spiced Rum",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-transcend-hidden",
            screwSkuGroup: "trex-transcend-screws",
            plugSkuGroup: "trex-transcend-plugs",
          },
          {
            name: "Island Mist",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-transcend-hidden",
            screwSkuGroup: "trex-transcend-screws",
            plugSkuGroup: "trex-transcend-plugs",
          },
        ],
      },
      {
        id: "trex-lineage",
        name: "Transcend Lineage",
        brand: "Trex",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 0.94,
        colors: [
          {
            name: "Rainier",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-lineage-hidden",
            screwSkuGroup: "trex-lineage-screws",
            plugSkuGroup: "trex-lineage-plugs",
          },
          {
            name: "Carmel",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-lineage-hidden",
            screwSkuGroup: "trex-lineage-screws",
            plugSkuGroup: "trex-lineage-plugs",
          },
          {
            name: "Weathered Teak",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-lineage-hidden",
            screwSkuGroup: "trex-lineage-screws",
            plugSkuGroup: "trex-lineage-plugs",
          },
          {
            name: "Biscayne",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-lineage-hidden",
            screwSkuGroup: "trex-lineage-screws",
            plugSkuGroup: "trex-lineage-plugs",
          },
          {
            name: "Pebble Beach",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-lineage-hidden",
            screwSkuGroup: "trex-lineage-screws",
            plugSkuGroup: "trex-lineage-plugs",
          },
          {
            name: "Jasper",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-lineage-hidden",
            screwSkuGroup: "trex-lineage-screws",
            plugSkuGroup: "trex-lineage-plugs",
          },
          {
            name: "Ember",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-lineage-hidden",
            screwSkuGroup: "trex-lineage-screws",
            plugSkuGroup: "trex-lineage-plugs",
          },
        ],
      },
      {
        id: "trex-signature",
        name: "Signature",
        brand: "Trex",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 1.0,
        colors: [
          {
            name: "Whidbey",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-signature-hidden",
            screwSkuGroup: "trex-signature-screws",
            plugSkuGroup: "trex-signature-plugs",
          },
          {
            name: "Ocotillo",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x8x12", "1x12x12"],
            hiddenFastenerSkuGroup: "trex-signature-hidden",
            screwSkuGroup: "trex-signature-screws",
            plugSkuGroup: "trex-signature-plugs",
          },
        ],
      },
    ],
  },
  {
    id: "timbertech",
    name: "TimberTech",
    collections: [
      {
        id: "tt-prime-plus",
        name: "Prime+",
        brand: "TimberTech",
        boardFaceWidthIn: 5.36,
        boardThicknessIn: 0.94,
        colors: [
          {
            name: "Coconut Husk",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-primeplus-hidden",
            screwSkuGroup: "tt-primeplus-screws",
            plugSkuGroup: "tt-primeplus-plugs",
          },
          {
            name: "Sea Salt Gray",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-primeplus-hidden",
            screwSkuGroup: "tt-primeplus-screws",
            plugSkuGroup: "tt-primeplus-plugs",
          },
          {
            name: "Dark Cocoa",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-primeplus-hidden",
            screwSkuGroup: "tt-primeplus-screws",
            plugSkuGroup: "tt-primeplus-plugs",
          },
        ],
      },
      {
        id: "tt-terrain",
        name: "Terrain+",
        brand: "TimberTech",
        boardFaceWidthIn: 5.36,
        boardThicknessIn: 0.94,
        colors: [
          {
            name: "Sandy Birch",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-terrain-hidden",
            screwSkuGroup: "tt-terrain-screws",
            plugSkuGroup: "tt-terrain-plugs",
          },
          {
            name: "Stone Ash",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-terrain-hidden",
            screwSkuGroup: "tt-terrain-screws",
            plugSkuGroup: "tt-terrain-plugs",
          },
          {
            name: "Silver Maple",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-terrain-hidden",
            screwSkuGroup: "tt-terrain-screws",
            plugSkuGroup: "tt-terrain-plugs",
          },
          {
            name: "Brown Oak",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-terrain-hidden",
            screwSkuGroup: "tt-terrain-screws",
            plugSkuGroup: "tt-terrain-plugs",
          },
          {
            name: "Rustic Elm",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-terrain-hidden",
            screwSkuGroup: "tt-terrain-screws",
            plugSkuGroup: "tt-terrain-plugs",
          },
        ],
      },
      {
        id: "tt-landmark",
        name: "Landmark",
        brand: "TimberTech",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 1.0,
        colors: [
          {
            name: "Boardwalk",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-landmark-hidden",
            screwSkuGroup: "tt-landmark-screws",
            plugSkuGroup: "tt-landmark-plugs",
          },
          {
            name: "French White Oak",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-landmark-hidden",
            screwSkuGroup: "tt-landmark-screws",
            plugSkuGroup: "tt-landmark-plugs",
          },
          {
            name: "Castle Gate",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-landmark-hidden",
            screwSkuGroup: "tt-landmark-screws",
            plugSkuGroup: "tt-landmark-plugs",
          },
          {
            name: "American Walnut",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "tt-landmark-hidden",
            screwSkuGroup: "tt-landmark-screws",
            plugSkuGroup: "tt-landmark-plugs",
          },
        ],
      },
    ],
  },
  {
    id: "deckorators",
    name: "Deckorators",
    collections: [
      {
        id: "deckorators-venture",
        name: "Venture",
        brand: "Deckorators",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 0.94,
        colors: [
          {
            name: "Saltwater",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-venture-hidden",
            screwSkuGroup: "deckorators-venture-screws",
            plugSkuGroup: "deckorators-venture-plugs",
          },
          {
            name: "Sandbar",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-venture-hidden",
            screwSkuGroup: "deckorators-venture-screws",
            plugSkuGroup: "deckorators-venture-plugs",
          },
          {
            name: "Shoreline",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-venture-hidden",
            screwSkuGroup: "deckorators-venture-screws",
            plugSkuGroup: "deckorators-venture-plugs",
          },
        ],
      },
      {
        id: "deckorators-voyage",
        name: "Voyage",
        brand: "Deckorators",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 0.94,
        colors: [
          {
            name: "Costa",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-voyage-hidden",
            screwSkuGroup: "deckorators-voyage-screws",
            plugSkuGroup: "deckorators-voyage-plugs",
          },
          {
            name: "Sierra",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-voyage-hidden",
            screwSkuGroup: "deckorators-voyage-screws",
            plugSkuGroup: "deckorators-voyage-plugs",
          },
          {
            name: "Khaya",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-voyage-hidden",
            screwSkuGroup: "deckorators-voyage-screws",
            plugSkuGroup: "deckorators-voyage-plugs",
          },
          {
            name: "Tundra",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-voyage-hidden",
            screwSkuGroup: "deckorators-voyage-screws",
            plugSkuGroup: "deckorators-voyage-plugs",
          },
          {
            name: "Sedona",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-voyage-hidden",
            screwSkuGroup: "deckorators-voyage-screws",
            plugSkuGroup: "deckorators-voyage-plugs",
          },
          {
            name: "Mesa",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-voyage-hidden",
            screwSkuGroup: "deckorators-voyage-screws",
            plugSkuGroup: "deckorators-voyage-plugs",
          },
        ],
      },
      {
        id: "deckorators-summit",
        name: "Summit",
        brand: "Deckorators",
        boardFaceWidthIn: 5.5,
        boardThicknessIn: 0.94,
        colors: [
          {
            name: "Glacier",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-summit-hidden",
            screwSkuGroup: "deckorators-summit-screws",
            plugSkuGroup: "deckorators-summit-plugs",
          },
          {
            name: "Boulder",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-summit-hidden",
            screwSkuGroup: "deckorators-summit-screws",
            plugSkuGroup: "deckorators-summit-plugs",
          },
          {
            name: "Cliffside",
            groovedLengthsFt: [12, 16, 20],
            solidLengthsFt: [20],
            fasciaOptions: ["1x12x12"],
            hiddenFastenerSkuGroup: "deckorators-summit-hidden",
            screwSkuGroup: "deckorators-summit-screws",
            plugSkuGroup: "deckorators-summit-plugs",
          },
        ],
      },
    ],
  },
];

// Railing systems catalog
export const railingSystems: RailingSystem[] = [
  {
    id: "vinyl-rail",
    material: "vinyl",
    label: "Vinyl Railing",
    colors: [{ name: "White" }, { name: "Clay" }, { name: "Khaki" }],
    levelSectionLengthsFt: [6, 8],
    stairSectionLengthsFt: [6, 8],
    levelPostHeightsIn: [39],
    stairPostHeightsIn: [45],
  },
  {
    id: "composite-rail",
    material: "composite",
    label: "Composite Railing",
    colors: [{ name: "White" }, { name: "Black" }, { name: "Brown" }],
    levelSectionLengthsFt: [6, 8],
    stairSectionLengthsFt: [6, 8],
    levelPostHeightsIn: [39],
    stairPostHeightsIn: [45],
  },
  {
    id: "aluminum-rail",
    material: "aluminum",
    label: "Aluminum Railing",
    colors: [{ name: "Black" }, { name: "Bronze" }, { name: "White" }],
    levelSectionLengthsFt: [6, 8],
    stairSectionLengthsFt: [6, 8],
    levelPostHeightsIn: [39],
    stairPostHeightsIn: [45],
  },
  {
    id: "cable-rail",
    material: "cable",
    label: "Cable Railing",
    colors: [{ name: "Black" }, { name: "Silver" }],
    levelSectionLengthsFt: [6, 8],
    stairSectionLengthsFt: [6, 8],
    levelPostHeightsIn: [39],
    stairPostHeightsIn: [45],
  },
];

// Lighting defaults
export const lightingDefaults = {
  watts: {
    postCap: 1.5,
    stair: 1.0,
    accent: 2.0,
  },
};

// Waste factors
export const wasteFactors = {
  framing: 0.05,
  decking: 0.07,
  fascia: 0.1,
  railing: 0.03,
};
