"use server";

import { createClient } from "@/lib/supabase/server";
import { getResend } from "@/lib/resend";
import { logActivity } from "@/lib/actions/activity";
import { revalidatePath } from "next/cache";

const FROM = process.env.FROM_EMAIL || "Deckmetry <notifications@deckmetry.com>";

interface ActionResult {
  success: boolean;
  error?: string;
}

async function loadEstimateForUser(estimateId: string) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" as const };

  const { data: profile } = await supabase
    .from("profiles")
    .select("default_organization_id")
    .eq("id", user.id)
    .single();
  const orgId = profile?.default_organization_id;
  if (!orgId) return { error: "No organization found" as const };

  const { data: estimate } = await supabase
    .from("estimates")
    .select(
      "id, organization_id, project_id, project_name, project_address, delivery_address, requested_delivery_date, contractor_name, scope, estimate_line_items(section, description, size, brand, color, quantity, unit, sort_order)"
    )
    .eq("id", estimateId)
    .is("deleted_at", null)
    .single();

  if (!estimate) return { error: "Estimate not found" as const };
  if (estimate.organization_id !== orgId) return { error: "Not authorized" as const };

  return { supabase, user, orgId, estimate };
}

/** Build a plain-text material list grouped by section. */
function renderBomText(estimate: {
  project_name?: string | null;
  project_address?: string | null;
  delivery_address?: string | null;
  requested_delivery_date?: string | null;
  contractor_name?: string | null;
  estimate_line_items?: {
    section?: string | null;
    description: string;
    size?: string | null;
    brand?: string | null;
    color?: string | null;
    quantity: number;
    unit: string;
    sort_order: number;
  }[];
}): string {
  const lines: string[] = [
    "DECKMETRY — MATERIAL LIST",
    "=".repeat(50),
    "",
    `Project: ${estimate.project_name || "Untitled"}`,
    `Contractor: ${estimate.contractor_name || "—"}`,
    `Address: ${estimate.project_address || "—"}`,
    `Delivery to: ${estimate.delivery_address || estimate.project_address || "—"}`,
    `Requested delivery: ${estimate.requested_delivery_date || "—"}`,
    "",
    "-".repeat(50),
    "",
  ];

  const items = [...(estimate.estimate_line_items ?? [])].sort((a, b) => a.sort_order - b.sort_order);
  const sections = new Map<string, typeof items>();
  for (const it of items) {
    const key = it.section || "Items";
    if (!sections.has(key)) sections.set(key, []);
    sections.get(key)!.push(it);
  }
  for (const [section, rows] of sections) {
    lines.push(section.toUpperCase());
    lines.push("-".repeat(30));
    for (const r of rows) {
      const size = r.size ? ` (${r.size})` : "";
      const bc = [r.brand, r.color].filter(Boolean).join(" ");
      const bcStr = bc ? ` {${bc}}` : "";
      lines.push(`  ${r.quantity} ${r.unit} — ${r.description}${size}${bcStr}`);
    }
    lines.push("");
  }
  lines.push("Generated by Deckmetry. Preliminary — verify before ordering.");
  return lines.join("\n");
}

/** Finish the material list: mark estimate completed + project BOM created. */
export async function finishMaterialList(estimateId: string): Promise<ActionResult> {
  const res = await loadEstimateForUser(estimateId);
  if ("error" in res) return { success: false, error: res.error };
  const { supabase, user, orgId, estimate } = res;

  await supabase.from("estimates").update({ status: "completed" }).eq("id", estimateId);
  if (estimate.project_id) {
    await supabase.from("projects").update({ status: "bom_created" }).eq("id", estimate.project_id);
  }
  await logActivity({
    orgId,
    userId: user.id,
    entityType: "estimate",
    entityId: estimateId,
    action: "completed",
    details: { projectName: estimate.project_name },
  });
  revalidatePath("/contractor/estimates");
  if (estimate.project_id) revalidatePath(`/contractor/projects/${estimate.project_id}`);
  return { success: true };
}

/** Email the material list to a supplier (defaults to the configured notification inbox). */
export async function emailBomToSupplier(
  estimateId: string,
  supplierEmail?: string
): Promise<ActionResult> {
  const res = await loadEstimateForUser(estimateId);
  if ("error" in res) return { success: false, error: res.error };
  const { supabase, user, orgId, estimate } = res;

  const to = (supplierEmail || process.env.INQUIRY_NOTIFICATION_EMAIL || "deckmetry@gmail.com").trim();
  const text = renderBomText(estimate);

  try {
    if (!process.env.RESEND_API_KEY) {
      return { success: false, error: "Email is not configured (missing RESEND_API_KEY)." };
    }
    const resend = getResend();
    const { error } = await resend.emails.send({
      from: FROM,
      to,
      subject: `Material List — ${estimate.project_name || "Deckmetry Project"}`,
      text,
      html: `<pre style="font-family:ui-monospace,Menlo,monospace;font-size:13px;line-height:1.5;white-space:pre-wrap;color:#0f172a">${text
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")}</pre>`,
    });
    if (error) return { success: false, error: String((error as { message?: string }).message ?? error) };
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : "Failed to send email" };
  }

  await logActivity({
    orgId,
    userId: user.id,
    entityType: "estimate",
    entityId: estimateId,
    action: "shared",
    details: { sentTo: to, projectName: estimate.project_name },
  });
  return { success: true };
}

/** Request a Wehrung's review: flag the project as estimate_requested + notify internally. */
export async function requestWehrungsReview(estimateId: string): Promise<ActionResult> {
  const res = await loadEstimateForUser(estimateId);
  if ("error" in res) return { success: false, error: res.error };
  const { supabase, user, orgId, estimate } = res;

  if (estimate.project_id) {
    await supabase
      .from("projects")
      .update({ status: "estimate_requested" })
      .eq("id", estimate.project_id);
  }

  // Internal notification (best-effort).
  try {
    if (process.env.RESEND_API_KEY) {
      const resend = getResend();
      await resend.emails.send({
        from: FROM,
        to: process.env.INQUIRY_NOTIFICATION_EMAIL || "deckmetry@gmail.com",
        subject: `Wehrung's review requested — ${estimate.project_name || "Project"}`,
        text: `${estimate.contractor_name || "A contractor"} requested a Wehrung's review.\n\n${renderBomText(estimate)}`,
      });
    }
  } catch (err) {
    console.error("[requestWehrungsReview] notify failed:", err);
  }

  await logActivity({
    orgId,
    userId: user.id,
    entityType: "estimate",
    entityId: estimateId,
    action: "review_requested",
    details: { projectName: estimate.project_name },
  });
  revalidatePath("/contractor/estimates");
  if (estimate.project_id) revalidatePath(`/contractor/projects/${estimate.project_id}`);
  return { success: true };
}
